# Generated by Django 5.2.17 on 2026-08-26 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Executive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('executive', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parties', to='core.executive')),
            ],
        ),
        migrations.CreateModel(
            name='MOU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.CharField(max_length=9)),
                ('annual_target', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('target_apr', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('target_may', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('target_jun', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('target_jul', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('target_aug', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('target_sep', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('target_oct', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('target_nov', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('target_dec', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('target_jan', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('target_feb', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('target_mar', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('achievement_apr', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('achievement_may', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('achievement_jun', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('achievement_jul', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('achievement_aug', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('achievement_sep', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('achievement_oct', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('achievement_nov', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('achievement_dec', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('achievement_jan', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('achievement_feb', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('achievement_mar', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('party', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mou', to='core.party')),
            ],
        ),
        migrations.CreateModel(
            name='Subproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subproducts', to='core.product')),
            ],
            options={
                'unique_together': {('product', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('month', models.PositiveSmallIntegerField()),
                ('fiscal_year', models.CharField(max_length=9)),
                ('warehouse', models.CharField(blank=True, max_length=150)),
                ('units', models.DecimalField(decimal_places=2, max_digits=12)),
                ('basic_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.party')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.product')),
                ('subproduct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.subproduct')),
            ],
            options={
                'indexes': [models.Index(fields=['party', 'month', 'fiscal_year'], name='core_invoic_party_i_876897_idx')],
            },
        ),
    ]
