# Generated by Django 5.2.17 on 2026-09-03 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='invoice_no',
            new_name='voucher_no',
        ),
    ]
