# Generated by Django 5.2.17 on 2026-09-04 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(max_length=255)),
                ('fiscal_year', models.CharField(max_length=9)),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial - completed with issues'), ('failed', 'Failed')], max_length=10)),
                ('invoice_rows_processed', models.PositiveIntegerField(default=0)),
                ('mou_rows_processed', models.PositiveIntegerField(default=0)),
                ('reconciliation_mismatches', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
