# Generated by Django 5.2.17 on 2026-09-05 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_rename_invoice_no_invoice_voucher_no'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('sales_head', 'Sales Head'), ('executive', 'Executive')], max_length=20)),
                ('executive', models.ForeignKey(blank=True, help_text="Required for the 'Executive' role - links this login to their party data.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.executive')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
